version: "3.9"
services:
  backend:
    build: ./backend
    environment:
      NODE_ENV: development
      PORT: ${BACKEND_PORT}
      DATABASE_URL: ${DATABASE_URL}
      STREAM_SECRET: ${STREAM_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
      MAX_UPLOAD_MB: ${MAX_UPLOAD_MB}
      DEFAULT_RTMP_URL: ${DEFAULT_RTMP_URL}
    volumes:
      - backend_uploads:/app/uploads
      - ./backend:/app
      - /app/node_modules
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db
    command: sh -c "npm install && npx nodemon server.js"
    
  frontend:
    image: node:20-bullseye
    working_dir: /app
    environment:
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "8080:5173"
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - ${DOCKER_PGSQL_PORT}:5432

volumes:
  db_data:
  backend_uploads:
  frontend_node_modules: